# Generated by Django 5.2 on 2025-05-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='medicos/'),
        ),
    ]
